### ISSUE TITLE
污染查询

### ISSUE THREAD

**Issue by CS-Tao** [CS-Tao/AQI-Visualization#3]
- 时间(日)
- 一个条形图：前 n 的 aqi 指数
- 平均污染指数
- 点击一个城市的条形图，地图移动，显示日历图
- 仪表盘，显示 aqi、pm2.5、SO2
- 点击地图对应城市，显示该城市的雷达属性图

**Comment by CS-Tao** [comment]
## 细节修改
@xibosun 
### bug
- [ ] 点击污染查询按钮时，需要立即加载图表
- [ ] 点击条形图之后，条形图宽度变小，但是再次选择时间，条形图宽度没有变化
- [ ] 条形图横坐标有误，并没有显示 10 个城市
### 样式
#### 仪表盘
- [ ] 样式采用省份统计的仪表盘主题
- [ ] 宽度调小一点，放到 LED 时间正上方，参考省份统计的仪表盘
#### 条形图
- [ ] legend 往上调一点
- [ ] 题目改为：`xxxx-xx-xx 全国污染最严重的十个城市`
- [ ] 和横坐标平行的线，颜色调低
- [ ] 和日历图的位置交换一下
#### 日历图
- [ ] legend 的第一个显示：`Aqi`(首字母大写)，最后一个显示：`当前日期`
- [ ] 在 tooltip 显示的数字前加上：`Aqi:`
- [ ] 当前选中的颜色用 `#5287c4`，把当前选中的半径调大一点，添加和 Top 10 一样的动画
- [ ] 点击日历图的某一天，切换全局变量到该天：‘this.$store.dispatch()’
- [ ] 所有的小圆半径再调大一点
#### 平均值显示控件
- [ ] 前十的平均值没什么意义，改为最大值，并在前面加上比较小的字：`AQI 峰值：`

**Comment by xibosun** [comment]
好的明天改
